comma_map={ "it's":"it is",
            "i'm":"i am",
            "don't":"do not",
            "i'll":'i will',
            "he's":"he is",
            "can't": "can not",
            "didn't":"dit not",
            "i've": "i have",
            "what's":"what is",
            "we're":"we are",
            "there's":"there is",
            "they're":"they are",
            "she's": "she is",
            "you've": "you have",
            "won't": "will not",
            "let's": "let us",
            "isn't": "is not",
            "doesn't":"does not",
            "you'll":"you will",
            "we'll":"we will",
            "wouldn't":"would not",
            "ain't":"aint",
            "wasn't": "was not",
            "you'd": "you would",
            "we've":"we have",
            "haven't":"have not",
            "couldn't": "could not",
            "who's":"who is",
            "aren't": "are not",
            "where's": "where is",
            "he'll": "he will",
            "it'll":"it will",
            "how's": "how is",
            "shouldn't": "should not",
            "weren't": "were not",
            "we'd": "we would",
            "he'd": "he would",
            "they've":"they have",
            "here's": "here is",
            "she'll": "she will",
            "how'd":"how would",
            "what'd": "what would",
            "hasn't": "has not",
            "they'd": "they would",
            "hadn't": "had not",
            "c'mon": "come on",
            "must've": "must have",
            "that'll":"that will",
            "should've":"should have",

            " hes ":"he is",
            " cant ": "can not",
            " didnt ":"dit not",
            " ive ": "i have",
            " theyre ":"they are",
            " youve ": "you have",
            " wont ": "will not",
            " isnt ": "is not",
            " doesnt ":"does not",
            " youll ":"you will",
            " wouldnt ":"would not",
            " wasnt ": "was not",
            " youd ": "you would",
            " weve ":"we have",
            " havent ":"have not",
            " couldnt ": "could not",
            " arent ": "are not",
            " itll ":"it will",
            " shouldnt ": "should not",
            " werent ": "were not",
            " theyve ":"they have",
            " heres ": "here is",
            " howd ":"how would",
            " whatd ": "what would",
            " cmon ": "come on"
            }